version: "3"

services:

  jupyter:
    build:
      context: ./src/jupyter
    container_name: jupyter
    ports:
      - 8888:8888
    volumes:
      - ./src/spending-tracker/:/src
      - ./src/jupyter/notebooks:/home/jovyan/notebooks
      - /Users/caleb.crouse/Downloads:/src/transaction_data/downloads
    environment:
      JUPYTER_ENABLE_LAB: "yes"

  spending-tracker:
    build:
      context: ./src/spending-tracker
    container_name: spending-tracker
    ports:
      - 8501:8501
    volumes:
      - /Users/caleb.crouse/Downloads:/src/transaction_data/downloads
      - ./src/spending-tracker:/src